### ISSUE TITLE
Add Details To Code of Conduct File

### ISSUE THREAD

**Issue by TeeOkome** [NPDebs/Pre-seeds-Program#1]
The code_of_conduct.md file is currently empty. I propose adding in the details to outline the expected behaviour of contributors clearly. 

**Expected Outcome:**

- Add the details of the code_of_conduct .md file to the repository's root directory. 
- Ensure that the guidelines are clear, inclusive, and representative of the project's values.

**Request**: 
Please assign this issue  to me, as I would like to contribute by filling up this file. 

**Labels**: 
Documentation, Enchancement

**Comment by NPDebs** [comment]
@TeeOkome - Congrats on opening issue #1! 🎉 I have assigned it to you. Thanks a lot!
